// Shaped like code generated by @hey-api/openapi-ts
import { client } from './client.gen';

export class InvoicesService {
  public static listInvoices(options?: { client?: typeof client }) {
    return (options?.client ?? client).get({
      responseType: 'json',
      url: '/api/invoices',
    });
  }
}
